on:
  release:
    types: [published]
name: Publish Release
jobs:
  release-linux-amd64:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.14.x
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build
        run: go build
        env:
          GO111MODULE: "on"
          GOARCH: "amd64"
          GOOS: "linux"
          CGO_ENABLED: "0"
      - name: Rename file
        run: mv github-status-publisher github-status-publisher-linux-amd64
      - name: Upload the artifact
        uses: skx/github-action-publish-binaries@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: "github-status-publisher-*"
