on:
  release:
    types: [published]
name: Publish Release
jobs:
  steps:
    release-linux-amd64:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.14.x
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build
        run: go build
        env:
          GO111MODULE: "on"
          GOARCH: "amd64"
          GOOS: "linux"
      - name: Rename file
        run: mv github-status-publisher github-status-publisher-linux-amd64
      - name: Upload the artifact
        uses: skx/github-action-publish-binaries@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with:
            args: "github-status-publisher-*"
